// Generated by CoffeeScript 1.3.2

/*
negotiator.coffee

A small tool for proxying objects behind a wrapper that can inject
parameters into their methods.

Usage:
  negotiator = require('negotiator')  --for node
  regular script tag for use in the browser.

  //negotiator(object, templateFunction)
  var x = someInstanceOfAClass;
  x.go = function(mission,speed,destination) {
    return [mission, speed, destination];
  }
  wrappedX = negotiator(x, function(speed, destination) {});
  wrappedX('fast','mars').go('victory') ==> ['victory','fast','mars']

  wrappedY = negotiator(x, function(speed, destination) {
    return {speed: 'warp', destination: destination}
  });
  wrappedY('fast','mars').go('victory') ==> ['victory','warp','mars']


Properties of the wrapper:
  __real__    : reference to the object being wrapped.
  __context__ : a map of the paramaters to be injected,
              : set by calling the wrapper.
              : from the above example ---
              : wrappedX.__context__ => {}
              : wrappedX('one','two').__context__ => { one: 1, two: 2 }
              : wrappedX.__context__ => still {}

Caveats:
  Injected parameters need to be at the end of the parameter list
  they can't be intersperced with regular parameters, or put them at the
  beginning and then have regular access to normal parameters. 
  It's not possible to definitively tell from a method call and from a method 
  description what the caller's intent is, so I opted not to guess.
  
  All the proxies are baked into the proxy when you call negotiator(),
  so don't expect to add any methods to an object afterwards and have them
  appear on the proxy.

  Non-method properties are not proxied, the proxied object's state is
  encapsulated. However, you can set them via any of their own proxied methods 
  or even the template function itself, if you so desired.

Copyright (c) 2012 [Kobie Maitland]
*/


(function() {
  var negotiator, utils, _;

  _ = require('underscore');

  utils = {};

  utils.parameterNames = function(func) {
    var funcArgs, k, _i, _len, _results;
    funcArgs = func.toString().split('(')[1].split(')')[0].split(',');
    _results = [];
    for (_i = 0, _len = funcArgs.length; _i < _len; _i++) {
      k = funcArgs[_i];
      _results.push(k.trim());
    }
    return _results;
  };

  utils.injectAndApply = function(func, parameters, context, target) {
    var name, position, signature;
    signature = utils.parameterNames(func);
    if (_.isEmpty(parameters)) {
      parameters = [];
    }
    for (position in signature) {
      name = signature[position];
      if (context[name] != null) {
        parameters[position] = context[name];
      }
    }
    return func.apply(target != null ? target : {}, parameters);
  };

  utils.Proxy = function(real) {
    var key, method, self;
    this.__real__ = real;
    self = this;
    for (key in real) {
      method = real[key];
      if (typeof method === 'function') {
        (function(method, key) {
          return self[key] = function() {
            var _ref;
            return utils.injectAndApply(method, arguments, (_ref = this.__context__) != null ? _ref : {}, this.__real__);
          };
        })(method, key);
      }
    }
    return this;
  };

  utils.buildContextFromParams = function(func, parameters) {
    var context, key, signature, value;
    signature = utils.parameterNames(func);
    context = {};
    for (key in parameters) {
      value = parameters[key];
      context[signature[key]] = value;
    }
    return context;
  };

  utils.innerWrapper = function(proxy, contextBuilder, parameters) {
    var wrapper, _ref;
    wrapper = function() {
      return utils.innerWrapper(proxy, contextBuilder, arguments);
    };
    wrapper.__context__ = (_ref = contextBuilder.apply(proxy, parameters)) != null ? _ref : utils.buildContextFromParams(contextBuilder, parameters);
    wrapper.__proto__ = proxy;
    return wrapper;
  };

  utils.makeWrapper = function(real, contextBuilder) {
    var proxy;
    proxy = new utils.Proxy(real);
    return utils.innerWrapper(proxy, contextBuilder, []);
  };

  negotiator = utils.makeWrapper;

  negotiator.utils = utils;

  if (module) {
    module.exports = negotiator;
  } else {
    window.negotiator = negotiator;
  }

  true;

}).call(this);
